"""Added

Revision ID: 02af211e6b9c
Revises: 63c6fe348d09
Create Date: 2025-07-17 14:34:53.282482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af211e6b9c'
down_revision = '63c6fe348d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('friendships')
    # ### end Alembic commands ###
