"""add skills and education to User

Revision ID: 63c6fe348d09
Revises: 5941fef82152
Create Date: 2025-07-16 20:46:05.040948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c6fe348d09'
down_revision = '5941fef82152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
